//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace congngheweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int id { get; set; }
        public string room_number { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual room_status room_status { get; set; }
    }
}
